services:
  docx_url_to_pdf:
    image: docx_url_to_pdf
    container_name: docx_url_to_pdf
    build: ./
    # entrypoint: ['yarn', 'start']
    environment:
      - CLEANUP_AUTOMATION_DRY_MODE=OFF
      - CLEANUP_AUTOMATION_INTERVAL_MS=50000
      - PORT=9999
      - FILE_MAX_AGE_IN_SECONDS=300
    ports:
      - "9999:9999"
    volumes:
      - ./src:/root/docx_url_to_pdf/src
      - ./fonts:/usr/share/fonts/custom # All custom fonts go here
    restart: always
